import argon2

KEY_DERIVATION_SALT_SIZE = 16
KEY_DERIVATION_THREADS = 16
KEY_DERIVATION_KEY_SIZE = 32
KEY_DERIVATION_ITERATIONS = 17
KEY_DERIVATION_MEMORY = 204800
KEY_DERIVATION_ARGON_TYPE = argon2.low_level.Type.ID

INTEGRITY_STAMP_HASH_SIZE = 64
INTEGRITY_STAMP_SALT_SIZE = 16
